# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca258c3a5adad460a50dc8641c1463d7d5707eb23cfd3bdd6d176bbdcdfa0a22a40ceda4adb37ec2bd93e586aef56c37a10b3a469263408cf4c59e6a6b1c8101

test:
  secret_key_base: 63b963ef4dba6ebf91a7cb45576919db7649e932776febca7535f223c9964e3ff6a544094a19d97b442350fe189103c320799ce91eb9917526e107ac81f690d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
